AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate Service for kjtxt-api with ALB integration

Parameters:
  ClusterName:
    Type: String
    Description: ECS Cluster Name
  ServiceName:
    Type: String
    Default: kjtxt-service
    Description: ECS Service Name
  TaskFamily:
    Type: String
    Default: kjtxt-api-task
    Description: ECS Task Definition Family
  ContainerName:
    Type: String
    Default: kjtxt-api
    Description: Container Name
  ContainerImage:
    Type: String
    Description: ECR Image URI
  ContainerPort:
    Type: Number
    Default: 8080
    Description: Port the container listens on
  Cpu:
    Type: String
    Default: '512'
    Description: CPU units for the task
  Memory:
    Type: String
    Default: '1024'
    Description: Memory (MiB) for the task
  ExecutionRoleArn:
    Type: String
    Description: IAM Role ARN for ECS Task Execution
  SubnetIds:
    Type: List<String>
    Description: List of subnet IDs
  SecurityGroupIds:
    Type: List<String>
    Description: List of security group IDs
  DesiredCount:
    Type: Number
    Default: 1
    Description: Number of tasks to run
  TargetGroupArn:
    Type: String
    Description: ARN of the ALB Target Group

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref TaskFamily
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref ExecutionRoleArn
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/kjtxt-api
              awslogs-region: ap-northeast-1
              awslogs-stream-prefix: ecs

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterName
      ServiceName: !Ref ServiceName
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      DesiredCount: !Ref DesiredCount
      EnableExecuteCommand: true
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups: !Ref SecurityGroupIds
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroupArn
          ContainerName: !Ref ContainerName
          ContainerPort: !Ref ContainerPort
