AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate Stack with ALB, IAM, and ECS Resources (VPC/Subnet/SG are external)

# -----------------------------
# パラメータ定義（外部VPC/サブネット/SGを利用）
# -----------------------------
Parameters:
  VpcId:
    Type: String
    Description: 既存のVPC ID

  Subnet1:
    Type: String
    Description: パブリックサブネット1のID

  Subnet2:
    Type: String
    Description: パブリックサブネット2のID

  ALBSecurityGroupId:
    Type: String
    Description: ALB用のセキュリティグループID

  ECSSecurityGroupId:
    Type: String
    Description: ECSタスク用のセキュリティグループID

# -----------------------------
# リソース定義
# -----------------------------
Resources:
  # CloudWatch Logs用のロググループ
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/kjtxt-api
      RetentionInDays: 14

  # ECSクラスター
  ECSCluster:
    Type: AWS::ECS::Cluster
  # タスク実行ロール（イメージ取得やログ出力用）
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  # アプリケーションがDynamoDBにアクセスするためのタスクロール
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-task-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: "*"  # 必要に応じてDynamoDBテーブルARNに限定可能

  # ECSタスク定義（Fargate用）
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: kjtxt-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn  # イメージ取得・ログ出力用
      TaskRoleArn: !GetAtt TaskRole.Arn                # アプリケーションのDynamoDBアクセス用
      ContainerDefinitions:
        - Name: kjtxt-api
          Image: 854878589422.dkr.ecr.ap-northeast-1.amazonaws.com/kjtxt-api:latest
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/kjtxt-api
              awslogs-region: ap-northeast-1
              awslogs-stream-prefix: ecs

  # ALBのターゲットグループ（ECSタスクを登録）
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /health
      HealthCheckPort: traffic-port

  # アプリケーションロードバランサー（ALB）
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - Ref: Subnet1
        - Ref: Subnet2
      SecurityGroups:
        - Ref: ALBSecurityGroupId
      Scheme: internet-facing
      Type: application
      IpAddressType: ipv4

  # ALBのリスナー（HTTP:80 → ターゲットグループへ転送）
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  # ECSサービス（Fargateでタスクを起動し、ALBに登録）
  ECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - Listener
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: kjtxt-service
      LaunchType: FARGATE
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - Ref: Subnet1
            - Ref: Subnet2
          SecurityGroups:
            - Ref: ECSSecurityGroupId
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroup
          ContainerName: kjtxt-api
          ContainerPort: 8080

# -----------------------------
# 出力情報（ALBのDNS名など）
# -----------------------------
Outputs:
  LoadBalancerDNS:
    Description: DNS name of the ALB
    Value: !GetAtt LoadBalancer.DNSName

  ECSClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster
